openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description:
    $ref: ../info-description.md
  termsOfService: https://www.extremenetworks.com/company/legal/terms-of-use/
  contact:
    name: Extreme Networks Support
    url: https://www.extremenetworks.com/support
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: https://extremecloudiq.com/api-docs/api-reference.html
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: https://api.extremecloudiq.com
tags:
  - name: Configuration - Policy
    description: SSID/User Profile/Classification Rule/CCG/Radio Profile/...
paths:
  /ccgs:
    $ref: paths/ccgs.yaml
  /ccgs/{id}:
    $ref: paths/ccgs_{id}.yaml
  /classification-rules:
    $ref: paths/classification-rules.yaml
  /classification-rules/{id}:
    $ref: paths/classification-rules_{id}.yaml
  /l3-address-profiles:
    $ref: paths/l3-address-profiles.yaml
  /radio-profiles:
    $ref: paths/radio-profiles.yaml
  /radio-profiles/mac-ouis:
    $ref: paths/radio-profiles_mac-ouis.yaml
  /radio-profiles/{id}:
    $ref: paths/radio-profiles_{id}.yaml
  /radio-profiles/wmm-qos/{id}:
    $ref: paths/radio-profiles_wmm-qos_{id}.yaml
  /radio-profiles/sensor-scan/{id}:
    $ref: paths/radio-profiles_sensor-scan_{id}.yaml
  /radio-profiles/radio-usage-opt/{id}:
    $ref: paths/radio-profiles_radio-usage-opt_{id}.yaml
  /radio-profiles/neighborhood-analysis/{id}:
    $ref: paths/radio-profiles_neighborhood-analysis_{id}.yaml
  /radio-profiles/miscellaneous/{id}:
    $ref: paths/radio-profiles_miscellaneous_{id}.yaml
  /radio-profiles/mac-ouis/{id}:
    $ref: paths/radio-profiles_mac-ouis_{id}.yaml
  /radio-profiles/channel-selection/{id}:
    $ref: paths/radio-profiles_channel-selection_{id}.yaml
  /ssids:
    $ref: paths/ssids.yaml
  /ssids/{id}/psk/password:
    $ref: paths/ssids_{id}_psk_password.yaml
  /ssids/{id}/mode/wep:
    $ref: paths/ssids_{id}_mode_wep.yaml
  /ssids/{id}/mode/psk:
    $ref: paths/ssids_{id}_mode_psk.yaml
  /ssids/{id}/mode/ppsk:
    $ref: paths/ssids_{id}_mode_ppsk.yaml
  /ssids/{id}/mode/open:
    $ref: paths/ssids_{id}_mode_open.yaml
  /ssids/{id}/mode/dot1x:
    $ref: paths/ssids_{id}_mode_dot1x.yaml
  /user-profiles:
    $ref: paths/user-profiles.yaml
  /user-profiles/{id}:
    $ref: paths/user-profiles_{id}.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
