type: object
description: The configuration deployment overview
required:
  - in_progress_devices
  - total_progress
properties:
  in_progress_devices:
    type: integer
    description: The device count with in progress deployment
    format: int32
  total_progress:
    type: integer
    description: The total progress, range from 0 to 100
    format: int32
