# See https://redocly.com/docs/cli/configuration/

lint:
  extends:
    - recommended
  rules:
    parameter-description: error
    no-ambiguous-paths: off
    operation-4xx-response: off
    operation-tag-defined: error
    assert/info-description:
      subject: Info
      property: description
      message: Info description must be at least 30 characters and end with a full stop.
      severity: error
      defined: true
      minLength: 30
      pattern: /\.$/
    assert/operation-summary:
      subject: Operation
      property: summary
      message: Operation summary must be between 10 and 50 characters and NOT end with a full stop.
      severity: error
      defined: true
      minLength: 10
      maxLength: 50
      pattern: /[^\.]$/
    assert/operation-description:
      subject: Operation
      property: description
      message: Operation description must be at least 20 characters and end with a full stop.
      severity: error
      defined: true
      minLength: 20
      pattern: /\.$/

features.openapi:
  hideDownloadButton: true
  pathInMiddlePanel: true
  requiredPropsFirst: true
  sideNavStyle: path-first
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Java
      - lang: Go
      - lang: Node.js
      - lang: Python