openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: HIQ
    description: Hierarchical ExtremeCloud IQ
paths:
  /hiq/context:
    $ref: paths/hiq_context.yaml
  /hiq/context/reading:
    $ref: paths/hiq_context_reading.yaml
  /hiq/context/creating:
    $ref: paths/hiq_context_creating.yaml
  /hiq/organizations:
    $ref: paths/hiq_organizations.yaml
  /hiq/organizations/{id}/:rename:
    $ref: paths/hiq_organizations_{id}_:rename.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
