openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description: ExtremeCloud IQ RESTful API for external and internal applications.
  termsOfService: 'https://www.extremenetworks.com/company/legal/terms-of-use/'
  contact:
    name: Extreme Networks Support
    url: 'https://www.extremenetworks.com/support'
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: 'https://extremecloudiq.com/api-docs/api-reference.html'
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: 'https://api.extremecloudiq.com'
tags:
  - name: Application
    description: Application management and application metrics
paths:
  /applications:
    get:
      tags:
        - Application
      summary: List the applications
      description: List a page of applications by filter.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_list_the_applications'
      operationId: listApplications
      parameters:
        - name: page
          in: query
          description: 'Page number, min = 1'
          required: false
          schema:
            minimum: 1
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: 'Page Size, min = 1, max = 100'
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 10
        - name: name
          in: query
          description: Application Name
          required: false
          schema:
            type: string
        - name: detectionProtocol
          in: query
          description: 'Application Detection Protocol, only for custom Application'
          required: false
          schema:
            $ref: '#/components/schemas/XiqApplicationDetectionProtocol'
        - name: detectionType
          in: query
          description: 'Application Detection Type, only for custom Application'
          required: false
          schema:
            $ref: '#/components/schemas/XiqApplicationDetectionType'
        - name: predefined
          in: query
          description: Flag to filter predefined or custom Application
          required: false
          schema:
            type: boolean
          example: true
        - name: sortField
          in: query
          description: The sort field
          required: false
          schema:
            $ref: '#/components/schemas/XiqApplicationSortField'
        - name: order
          in: query
          description: The sort order (ascending by default)
          required: false
          schema:
            $ref: 'common/common.yaml#/components/schemas/XiqSortOrder'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedXiqApplication'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/applications/{id}/clients/top{n}':
    get:
      tags:
        - Application
      summary: List the TopN clients for a application
      description: List the TopN clients by usage for a specific application.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_list_top_n_clients_usage_for_one_application'
      operationId: listApplicationTopClientsUsage
      parameters:
        - name: id
          in: path
          description: The application ID
          required: true
          schema:
            type: integer
            format: int64
        - name: 'n'
          in: path
          description: The TopN number
          required: true
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
        - name: startTime
          in: query
          description: The start time for querying top client usage of application
          required: true
          schema:
            type: integer
            format: int64
        - name: endTime
          in: query
          description: The end time for querying top application usage of application
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XiqApplicationTopClientsUsage'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/applications/top{n}':
    get:
      tags:
        - Application
      summary: List the TopN applications
      description: List the TopN applications by usage.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_list_top_n_applications_usage'
      operationId: listTopApplicationsUsage
      parameters:
        - name: 'n'
          in: path
          description: The TopN number
          required: true
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
        - name: startTime
          in: query
          description: The start time for querying top application usage
          required: true
          schema:
            type: integer
            format: int64
        - name: endTime
          in: query
          description: The end time for querying top application usage
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XiqTopApplicationsUsage'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    XiqApplicationDetectionProtocol:
      type: string
      enum:
        - HTTP
        - HTTPS
    XiqApplicationDetectionType:
      type: string
      enum:
        - HOST_NAME
        - SERVER_IP_ADDRESS
        - PORT_NUMBER
    XiqApplicationSortField:
      type: string
      enum:
        - NAME
        - CATEGORY
    PagedXiqApplication:
      required:
        - count
        - page
        - total_count
        - total_pages
      type: object
      properties:
        page:
          type: integer
          description: The current page number
          format: int32
        count:
          type: integer
          description: The element count of the current page
          format: int32
        total_pages:
          type: integer
          description: The total page number based on request page size
          format: int32
        total_count:
          type: integer
          description: The total element count
          format: int64
        data:
          type: array
          description: The data in the current page
          items:
            $ref: '#/components/schemas/XiqApplication'
    XiqApplication:
      required:
        - create_time
        - id
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        org_id:
          type: integer
          description: 'The organization identifier, valid when enabling HIQ feature'
          format: int64
        name:
          type: string
          description: The application name
        description:
          type: string
          description: The application description
        predefined:
          type: boolean
          description: Flag to describle whether the application is predefined or customized
        category_id:
          type: integer
          description: The category ID of application
          format: int64
        category_name:
          type: string
          description: The category name of application
        detection_rules:
          type: array
          description: The application detection rules
          items:
            $ref: '#/components/schemas/XiqApplicationDetectionRule'
      description: The Application Model
    XiqApplicationDetectionRule:
      type: object
      properties:
        value:
          type: string
          description: The value of detection rule type
        protocol:
          $ref: '#/components/schemas/XiqApplicationDetectionProtocol'
        type:
          $ref: '#/components/schemas/XiqApplicationDetectionType'
      description: The Application Detection Rule
    XiqApplicationTopClientsUsage:
      type: object
      properties:
        application_id:
          type: integer
          description: The application ID
          format: int64
        client_id:
          type: integer
          description: The TOP N client ID
          format: int64
        client_mac_address:
          type: string
          description: The MAC address of TOP N client
        client_host_name:
          type: string
          description: The host name of TOP N client
        usage:
          type: integer
          description: The TOP N client usage
          format: int64
      description: The Top N Clients Usage per Application
    XiqTopApplicationsUsage:
      type: object
      properties:
        id:
          type: integer
          description: The application ID
          format: int64
        name:
          type: string
          description: The application name
        clients:
          type: integer
          description: The associated unique client count
          format: int64
        users:
          type: integer
          description: The associated unique user count
          format: int64
        usage:
          type: integer
          description: The application usage
          format: int64
      description: The Top N Applications Usage
