openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description: ExtremeCloud IQ RESTful API for external and internal applications.
  termsOfService: 'https://www.extremenetworks.com/company/legal/terms-of-use/'
  contact:
    name: Extreme Networks Support
    url: 'https://www.extremenetworks.com/support'
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: 'https://extremecloudiq.com/api-docs/api-reference.html'
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: 'https://api.extremecloudiq.com'
tags:
  - name: Client
    description: The clients associate to the devices of ExtremeCloud IQ
paths:
  '/clients/{id}':
    get:
      tags:
        - Client
      summary: Get client info
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_client_details_for_one_client'
      operationId: getClient
      description: Get client detailed information.
      parameters:
        - name: id
          in: path
          description: The client ID
          required: true
          schema:
            type: integer
            format: int64
        - name: views
          in: query
          description: The views to return client fields (Check fields for each view at XiqClientView schema)
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/XiqClientView'
        - name: fields
          in: query
          description: The client fields to return
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/XiqClientField'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqClient'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  /clients/usage:
    get:
      tags:
        - Client
      summary: Get usage per client
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_client_usage'
      operationId: getClientUsage
      description: Get the client usage.
      parameters:
        - name: clientIds
          in: query
          description: The client IDs
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: startTime
          in: query
          description: 'The start time to query, epoch time in milliseconds since 1/1/1970'
          required: true
          schema:
            type: integer
            format: int64
        - name: endTime
          in: query
          description: 'The end time to query, epoch time in milliseconds since 1/1/1970'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XiqClientUsage'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  /clients/summary:
    get:
      tags:
        - Client
      summary: Get client summary metrics
      description: Get number of connected wireless clients and number of detected wired clients.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_client_summary'
      operationId: getClientSummary
      parameters:
        - name: locationIds
          in: query
          description: The location IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: deviceIds
          in: query
          description: The device IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: vlans
          in: query
          description: The associate VLAN IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: userProfileNames
          in: query
          description: The user profile names
          required: false
          schema:
            type: array
            items:
              type: string
        - name: ssids
          in: query
          description: The SSIDs
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqClientSummary'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  /clients/active:
    get:
      tags:
        - Client
      summary: List active clients
      description: List active clients with filters and pagination.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_client_list'
      operationId: listActiveClients
      parameters:
        - name: locationIds
          in: query
          description: The location IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: deviceIds
          in: query
          description: The device IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
        - name: vlans
          in: query
          description: The associate vlan IDs
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: userProfileNames
          in: query
          description: The user profile names
          required: false
          schema:
            type: array
            items:
              type: string
        - name: ssids
          in: query
          description: The SSIDs
          required: false
          schema:
            type: array
            items:
              type: string
        - name: page
          in: query
          description: 'Page number, min = 1'
          required: false
          schema:
            minimum: 1
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: 'Page Size, min = 1, max = 100'
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 10
        - name: views
          in: query
          description: The views to return client fields (Check fields for each view at XiqClientView schema)
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/XiqClientView'
        - name: fields
          in: query
          description: The client fields to return
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/XiqClientField'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedXiqClient'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    XiqClientView:
      type: string
      description: 'The logic collections of client fields<br/><br/><b>BASIC:</b> ID, ORG_ID, HOSTNAME, MAC_ADDRESS, IP_ADDRESS, IPV6_ADDRESS, OS_TYPE, DEVICE_ID,CONNECTED, ONLINE_TIME, OFFLINE_TIME, CONNECTION_TYPE, SSID, PORT<br/><b>FULL:</b> All fields<br/><b>STATUS:</b> ID, CONNECTED, ONLINE_TIME, OFFLINE_TIME<br/><b>DETAIL:</b> ID, CREATE_TIME, UPDATE_TIME, ORG_ID, ORG_NAME, LOCATION_ID, HOSTNAME,MAC_ADDRESS, IP_ADDRESS, IPV6_ADDRESS, OS_TYPE, DEVICE_ID, DEVICE_FUNCTION,DEVICE_NAME, DEVICE_MAC_ADDRESS, USERNAME, USER_PROFILE_NAME, CONNECTED, ONLINE_TIME, OFFLINE_TIME, VLAN, CONNECTION_TYPE, SSID, PORT, BSSID, PORT_TYPE_NAME, INTERFACE_NAME, AUTH, ENCRYPTION_METHOD, CHANNEL, RSSI, SNR, WING_AP, VENDOR, RADIO_TYPE<br/><b>LOCATION:</b> ID, LOCATION_ID, LOCATIONS<br/><b>METRICS:</b> ID, CLIENT_HEALTH, APPLICATION_HEALTH, NETWORK_HEALTH, RADIO_HEALTH<br/><b>IOT:</b> ID, MOBILITY, CATEGORY, DESCRIPTION'
      enum:
        - BASIC
        - FULL
        - STATUS
        - DETAIL
        - LOCATION
        - METRICS
        - IOT
    XiqClientField:
      type: string
      enum:
        - ID
        - CREATE_TIME
        - UPDATE_TIME
        - ORG_ID
        - ORG_NAME
        - LOCATION_ID
        - LOCATIONS
        - HOSTNAME
        - MAC_ADDRESS
        - IP_ADDRESS
        - IPV6_ADDRESS
        - OS_TYPE
        - DEVICE_ID
        - DEVICE_FUNCTION
        - DEVICE_NAME
        - USERNAME
        - USER_PROFILE_NAME
        - CONNECTED
        - ONLINE_TIME
        - OFFLINE_TIME
        - VLAN
        - CONNECTION_TYPE
        - SSID
        - PORT
        - BSSID
        - PORT_TYPE_NAME
        - INTERFACE_NAME
        - AUTH
        - ENCRYPTION_METHOD
        - CHANNEL
        - CLIENT_HEALTH
        - APPLICATION_HEALTH
        - NETWORK_HEALTH
        - RADIO_HEALTH
        - HEALTH_UPDATE_TIME
        - RSSI
        - RSSI_UPDATE_TIME
        - SNR
        - SNR_UPDATE_TIME
        - RADIO_TYPE
        - WING_AP
        - VENDOR
        - MOBILITY
        - CATEGORY
        - DESCRIPTION
        - DEVICE_MAC_ADDRESS
    XiqClient:
      required:
        - create_time
        - id
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        org_id:
          type: integer
          description: 'The organization identifier, valid when enabling HIQ feature'
          format: int64
        location_id:
          type: integer
          description: The location ID
          format: int64
        device_id:
          type: integer
          description: The device ID
          format: int64
        hostname:
          type: string
          description: The hostname of the client
        mac_address:
          type: string
          description: The MAC address of the client
        ip_address:
          type: string
          description: The IP address of the client
        ipv6_address:
          type: string
          description: The IPv6 address of the client
        os_type:
          type: string
          description: The OS type of the client
        username:
          type: string
          description: The username of the client.
        user_profile_name:
          type: string
          description: The user profile name of the client
        connected:
          type: boolean
          description: Client is connected or not
        online_time:
          type: string
          description: The online time for the client
          format: date-time
        offline_time:
          type: string
          description: The offline time for the client
          format: date-time
        vlan:
          type: integer
          description: The associate VLAN
          format: int32
        connection_type:
          type: integer
          description: The connection type
          format: int32
        ssid:
          type: string
          description: The SSID
        port:
          type: string
          description: The associate device port
        org_name:
          type: string
          description: The organization name
        device_function:
          type: integer
          description: The associated device function
          format: int32
        device_mac_address:
          type: string
          description: The associated device mac address
        device_name:
          type: string
          description: The associated device name
        auth:
          type: integer
          description: The authentication type
          format: int32
        channel:
          type: integer
          description: The channel value
          format: int32
        client_health:
          type: integer
          description: The health score of client
          format: int32
        application_health:
          type: integer
          description: The health score of application
          format: int32
        radio_health:
          type: integer
          description: The health score of radio
          format: int32
        network_health:
          type: integer
          description: The health score of network
          format: int32
        radio_type:
          type: integer
          description: The radio type
          format: int32
        encryption_method:
          type: integer
          description: The encryption method
          format: int32
        interface_name:
          type: string
          description: The interface name
        bssid:
          type: string
          description: The bssid
        rssi:
          type: integer
          description: The RSSI
          format: int32
        snr:
          type: integer
          description: The SNR
          format: int32
        description:
          type: string
          description: The description of client
        category:
          type: string
          description: The category of client
        mobility:
          type: string
          description: The client mobility
        port_type_name:
          type: string
          description: The client port type name
        wing_ap:
          type: boolean
          description: Wing ap flag
        vendor:
          type: string
          description: The vendor of client
        locations:
          type: array
          description: The detailed location
          items:
            $ref: 'device.yaml#/components/schemas/XiqLocationLegend'
      description: The Client associate to ExtremeCloud IQ device
    XiqClientUsage:
      type: object
      properties:
        client_id:
          type: integer
          description: The client ID
          format: int64
        usage:
          type: integer
          description: The client total usage
          format: int64
      description: The client usage over the period
    XiqClientSummary:
      type: object
      properties:
        connected_wireless_client_count:
          type: integer
          description: The connected wireless client count
          format: int64
        detected_wired_client_count:
          type: integer
          description: The detected wired client count
          format: int64
      description: The summary for clients
    PagedXiqClient:
      required:
        - count
        - page
        - total_count
        - total_pages
      type: object
      properties:
        page:
          type: integer
          description: The current page number
          format: int32
        count:
          type: integer
          description: The element count of the current page
          format: int32
        total_pages:
          type: integer
          description: The total page number based on request page size
          format: int32
        total_count:
          type: integer
          description: The total element count
          format: int64
        data:
          type: array
          description: The data in the current page
          items:
            $ref: '#/components/schemas/XiqClient'
