openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description: ExtremeCloud IQ RESTful API for external and internal applications.
  termsOfService: 'https://www.extremenetworks.com/company/legal/terms-of-use/'
  contact:
    name: Extreme Networks Support
    url: 'https://www.extremenetworks.com/support'
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: 'https://extremecloudiq.com/api-docs/api-reference.html'
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: 'https://api.extremecloudiq.com'
tags:
  - name: Configuration - Certificate
    description: Certificate
paths:
  /certificates:
    get:
      tags:
        - Configuration - Certificate
      summary: List certificates
      description: List a page of certificates.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_list_certificates'
      operationId: listCertificates
      parameters:
        - name: page
          in: query
          description: 'Page number, min = 1'
          required: false
          schema:
            minimum: 1
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: 'Page Size, min = 1, max = 100'
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 10
        - name: certType
          in: query
          description: The certificate type
          required: false
          schema:
            $ref: '#/components/schemas/XiqCertificateType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedXiqCertificate'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    XiqCertificateType:
      type: string
      enum:
        - CERT
        - KEY
    PagedXiqCertificate:
      required:
        - count
        - page
        - total_count
        - total_pages
      type: object
      properties:
        page:
          type: integer
          description: The current page number
          format: int32
        count:
          type: integer
          description: The element count of the current page
          format: int32
        total_pages:
          type: integer
          description: The total page number based on request page size
          format: int32
        total_count:
          type: integer
          description: The total element count
          format: int64
        data:
          type: array
          description: The data in the current page
          items:
            $ref: '#/components/schemas/XiqCertificate'
    XiqCertificate:
      required:
        - create_time
        - id
        - name
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        cert_type:
          $ref: '#/components/schemas/XiqCertificateType'
        name:
          type: string
          description: The certificate file name
      description: The data in the current page
