openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description: ExtremeCloud IQ RESTful API for external and internal applications.
  termsOfService: 'https://www.extremenetworks.com/company/legal/terms-of-use/'
  contact:
    name: Extreme Networks Support
    url: 'https://www.extremenetworks.com/support'
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: 'https://extremecloudiq.com/api-docs/api-reference.html'
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: 'https://api.extremecloudiq.com'
tags:
  - name: Location
    description: Hierarchical locations and floor plan
paths:
  '/locations/{id}':
    put:
      tags:
        - Location
      summary: Update location
      description: Update the location information with the specified location ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_update_location'
      operationId: updateLocation
      parameters:
        - name: id
          in: path
          description: The location ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update location request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqUpdateLocationRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqLocation'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags:
        - Location
      summary: Delete location by ID
      description: Delete the location for the specified ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_delete_location'
      operationId: deleteLocation
      parameters:
        - name: id
          in: path
          description: The location ID
          required: true
          schema:
            type: integer
            format: int64
        - name: force_delete
          in: query
          description: Force deletion of this location and its descendants recursively
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/locations/floor/{id}':
    put:
      tags:
        - Location
      summary: Update floor
      description: Update floor information with the floor ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_update_floor'
      operationId: updateFloor
      parameters:
        - name: id
          in: path
          description: The floor ID.
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update floor request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqUpdateFloorRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqFloor'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags:
        - Location
      summary: Delete floor by ID
      description: Delete the floor for the specified ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_delete_floor'
      operationId: deleteFloor
      parameters:
        - name: id
          in: path
          description: The floor ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/locations/building/{id}':
    put:
      tags:
        - Location
      summary: Update building
      description: Update the building information with the building ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_update_building'
      operationId: updateBuilding
      parameters:
        - name: id
          in: path
          description: The building ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update building request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqUpdateBuildingRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqBuilding'
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags:
        - Location
      summary: Delete building by ID
      description: Delete the building for the specified ID.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_delete_building'
      operationId: deleteBuilding
      parameters:
        - name: id
          in: path
          description: The building ID
          required: true
          schema:
            type: integer
            format: int64
        - name: force_delete
          in: query
          description: Force deletion of this building and its descendants recursively
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
        default:
          $ref: 'common/components.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    XiqUpdateLocationRequest:
      type: object
      properties:
        parent_id:
          type: integer
          description: The parent location ID
          format: int64
        name:
          type: string
          description: The location name
    XiqLocation:
      required:
        - create_time
        - id
        - name
        - type
        - unique_name
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        org_id:
          type: integer
          description: 'The organization identifier, valid when enabling HIQ feature'
          format: int64
        parent_id:
          type: integer
          description: The parent location ID
          format: int64
        name:
          type: string
          description: The location name
        unique_name:
          type: string
          description: The unique location name
        type:
          type: string
          description: The location type
        address:
          type: string
          description: The address for the location
        children:
          type: array
          description: The child locations
          items:
            $ref: '#/components/schemas/XiqLocation'
      description: The hierarchical location for Generic/Building/Floor
    XiqMeasurementUnit:
      type: string
      description: The measurement unit in feet/meters
      enum:
        - FEET
        - METERS
    XiqRfEnvironmentType:
      type: string
      description: The floor RF environment
      enum:
        - AUTO_ESTIMATE
        - OFFICE
        - OUTDOOR_FREE_SPACE
        - OBSTRUCTED_IN_BUILDING
        - OUTDOOR_SUBURBAN
        - WAREHOUSE
        - OUTDOOR_DENSE_URBAN
    XiqUpdateFloorRequest:
      type: object
      properties:
        parent_id:
          type: integer
          description: The parent building ID
          format: int64
        name:
          type: string
          description: The floor name
        environment:
          $ref: '#/components/schemas/XiqRfEnvironmentType'
        db_attenuation:
          type: number
          description: The floor attenuation in dBs
          format: double
        measurement_unit:
          $ref: '#/components/schemas/XiqMeasurementUnit'
        installation_height:
          type: number
          description: The installation height
          format: double
        map_size_width:
          type: number
          description: The floor map width
          format: double
        map_size_height:
          type: number
          description: The floor map height
          format: double
        map_name:
          type: string
          description: The floor map name
    XiqFloor:
      required:
        - create_time
        - db_attenuation
        - environment
        - id
        - installation_height
        - measurement_unit
        - name
        - parent_id
        - unique_name
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        org_id:
          type: integer
          description: 'The organization identifier, valid when enabling HIQ feature'
          format: int64
        parent_id:
          type: integer
          description: The parent building ID
          format: int64
        name:
          type: string
          description: The floor name
        unique_name:
          type: string
          description: The floor unique name
        environment:
          $ref: '#/components/schemas/XiqRfEnvironmentType'
        db_attenuation:
          type: number
          description: The floor attenuation in dBs
          format: double
        measurement_unit:
          $ref: '#/components/schemas/XiqMeasurementUnit'
        installation_height:
          type: number
          description: The installation height
          format: double
        map_size_width:
          type: number
          description: The floormap width
          format: double
        map_size_height:
          type: number
          description: The floormap height
          format: double
        map_name:
          type: string
          description: The floormap name
      description: The Floor information on the floorplan.
    XiqUpdateBuildingRequest:
      type: object
      properties:
        parent_id:
          type: integer
          description: The parent location ID
          format: int64
        name:
          type: string
          description: The building name
        address:
          type: string
          description: The street address
    XiqBuilding:
      required:
        - address
        - create_time
        - id
        - name
        - parent_id
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        org_id:
          type: integer
          description: 'The organization identifier, valid when enabling HIQ feature'
          format: int64
        parent_id:
          type: integer
          description: The parent location ID
          format: int64
        name:
          type: string
          description: The building name
        address:
          type: string
          description: The building street address
      description: The Building information on the floorplan.
