openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description: ExtremeCloud IQ RESTful API for external and internal applications.
  termsOfService: 'https://www.extremenetworks.com/company/legal/terms-of-use/'
  contact:
    name: Extreme Networks Support
    url: 'https://www.extremenetworks.com/support'
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: 'https://extremecloudiq.com/api-docs/api-reference.html'
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: 'https://api.extremecloudiq.com'
tags:
  - name: User
    description: Local and external user management in ExtremeCloud IQ account
paths:
  /users:
    get:
      tags:
        - User
      summary: List all users
      description: List users with pagination.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_user_list'
      operationId: listUsers
      parameters:
        - name: page
          in: query
          description: 'Page number, min = 1'
          required: false
          schema:
            minimum: 1
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: 'Page Size, min = 1, max = 100'
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedXiqUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    post:
      tags:
        - User
      summary: Create new user
      description: Create a new user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_create_new_user'
      operationId: createUser
      requestBody:
        description: Create new user request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqCreateUserRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  /users/external:
    get:
      tags:
        - User
      summary: List external access users
      description: List a page of external access users.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_external_user_list'
      operationId: listExternalUsers
      parameters:
        - name: page
          in: query
          description: 'Page number, min = 1'
          required: false
          schema:
            minimum: 1
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          description: 'Page Size, min = 1, max = 100'
          required: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedXiqExternalUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    post:
      tags:
        - User
      summary: Grant external access
      description: Grant external access to a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_grant_external_user'
      operationId: grantExternalUser
      requestBody:
        description: Grant external user request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqGrantExternalUserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqExternalUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/users/{id}':
    get:
      tags:
        - User
      summary: Get user info by ID
      description: Get user info for a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_user'
      operationId: getUser
      parameters:
        - name: id
          in: path
          description: The user ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags:
        - User
      summary: Delete user by ID
      description: Delete a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_delete_user'
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: The user ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    patch:
      tags:
        - User
      summary: Update user info
      description: Updates user info for a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_update_user'
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: The user ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update user request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqUpdateUserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  '/users/external/{id}':
    get:
      tags:
        - User
      summary: Get external access info
      description: Get external access info for a specific external user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_external_user'
      operationId: getExternalUser
      parameters:
        - name: id
          in: path
          description: The external user ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqExternalUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags:
        - User
      summary: Revoke external access
      description: Revoke external acccess for a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_revoke_external_user'
      operationId: revokeExternalUser
      parameters:
        - name: id
          in: path
          description: The external user ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
    patch:
      tags:
        - User
      summary: Update external access info
      description: Updates external access info for a specific user.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_update_external_user'
      operationId: updateExternalUser
      parameters:
        - name: id
          in: path
          description: The external user ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update external user request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/XiqUpdateExternalUserRequest'
            examples:
              Update external user info.:
                description: Update external user info.
                value:
                  user_role: ADMINISTRATOR
        required: true
      responses:
        '200':
          description: OK
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
  /users/me:
    get:
      tags:
        - User
      summary: Get current user info
      description: Get currently login user info.
      externalDocs:
        description: API Reference
        url: 'https://extremecloudiq.com/api-docs/api-reference.html#_get_current_user'
      operationId: getCurrentUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XiqUser'
        default:
          $ref: 'common/common.yaml#/components/responses/ErrorResponse'
      security:
        - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PagedXiqUser:
      required:
        - count
        - page
        - total_count
        - total_pages
      type: object
      properties:
        page:
          type: integer
          description: The current page number
          format: int32
        count:
          type: integer
          description: The element count of the current page
          format: int32
        total_pages:
          type: integer
          description: The total page number based on request page size
          format: int32
        total_count:
          type: integer
          description: The total element count
          format: int64
        data:
          type: array
          description: The data in the current page
          items:
            $ref: '#/components/schemas/XiqUser'
    PagedXiqExternalUser:
      required:
        - count
        - page
        - total_count
        - total_pages
      type: object
      properties:
        page:
          type: integer
          description: The current page number
          format: int32
        count:
          type: integer
          description: The element count of the current page
          format: int32
        total_pages:
          type: integer
          description: The total page number based on request page size
          format: int32
        total_count:
          type: integer
          description: The total element count
          format: int64
        data:
          type: array
          description: The data in the current page
          items:
            $ref: '#/components/schemas/XiqExternalUser'
    XiqCreateUserRequest:
      required:
        - display_name
        - login_name
        - user_role
      type: object
      properties:
        login_name:
          type: string
          description: 'Login name, i.e. username or login Email'
        display_name:
          type: string
          description: The user name to display
        idle_timeout:
          type: integer
          description: 'The idle timeout in minutes, the minimum value is 5 minutes and the maximum value is 4 hours'
          format: int32
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
    XiqUserRole:
      type: string
      description: The user administrative role.
      enum:
        - ADMINISTRATOR
        - OPERATOR
        - MONITOR
        - HELP_DESK
        - GUEST_MANAGEMENT
        - OBSERVER
        - INSTALLER
        - APPLICATION_OPERATOR
    XiqUser:
      required:
        - create_time
        - id
        - login_name
        - update_time
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        login_name:
          type: string
          description: 'Login name, i.e. username or login Email'
        first_name:
          type: string
          description: The first name
        last_name:
          type: string
          description: 'The last name, i.e. family name'
        display_name:
          type: string
          description: The name to display
        phone:
          type: string
          description: The Phone Number
        job_title:
          type: string
          description: The job title
        locale:
          type: string
          description: The locale
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
        idle_timeout:
          type: integer
          description: 'The idle timeout in minutes, the minimum value is 5 minutes and the maximum value is 4 hours'
          format: int32
        last_login_time:
          type: string
          description: The last login time
          format: date-time
        org_id:
          type: integer
          description: The HIQ organization ID if it is HIQ user
          format: int64
    XiqGrantExternalUserRequest:
      required:
        - login_name
        - user_role
      type: object
      properties:
        login_name:
          type: string
          description: 'Login name, i.e. username or login Email'
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
        org_id:
          type: integer
          description: 'The HIQ organization ID if it is HIQ user, otherwise leave it as empty'
          format: int64
        enable_api_access:
          type: boolean
          description: 'Whether to enable API access, false by default'
    XiqExternalUser:
      required:
        - create_time
        - id
        - login_name
        - update_time
        - user_role
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier
          format: int64
        create_time:
          type: string
          description: The create time
          format: date-time
        update_time:
          type: string
          description: The last update time
          format: date-time
        login_name:
          type: string
          description: 'Login name, i.e. username or login Email'
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
        org_id:
          type: integer
          description: The HIQ organization ID if it is HIQ user.
          format: int64
        enable_api_access:
          type: boolean
          description: Whether to enable API access.
    XiqUpdateUserRequest:
      type: object
      properties:
        login_name:
          type: string
          description: 'Login name, i.e. username or login Email'
        display_name:
          type: string
          description: The user name to display
        idle_timeout:
          type: integer
          description: 'The idle timeout in minutes, the minimum value is 5 minutes and the maximum value is 4 hours'
          format: int32
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
    XiqUpdateExternalUserRequest:
      type: object
      properties:
        user_role:
          $ref: '#/components/schemas/XiqUserRole'
        org_id:
          type: integer
          description: 'The HIQ organization ID if it is HIQ user, otherwise leave it as empty.'
          format: int64
        enable_api_access:
          type: boolean
          description: 'Whether to enable API access, false by default.'
