openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Client
    description: The clients associate to the devices of ExtremeCloud IQ
paths:
  /clients/active:
    $ref: paths/clients_active.yaml
  /clients/summary:
    $ref: paths/clients_summary.yaml
  /clients/usage:
    $ref: paths/clients_usage.yaml
  /clients/{id}:
    $ref: paths/clients_{id}.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
