openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description:
    $ref: ../info-description.md
  termsOfService: https://www.extremenetworks.com/company/legal/terms-of-use/
  contact:
    name: Extreme Networks Support
    url: https://www.extremenetworks.com/support
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: https://extremecloudiq.com/api-docs/api-reference.html
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: https://api.extremecloudiq.com
tags:
  - name: Notification
    description: Push events/logs to users via Webhook, Email, SMS, etc.
paths:
  /subscriptions/webhook:
    $ref: paths/subscriptions_webhook.yaml
  /subscriptions/webhook/{id}:
    $ref: paths/subscriptions_webhook_{id}.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
