openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  description: API Reference
  url: https://extremecloudiq.com/api-docs/api-reference.html
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: https://api.extremecloudiq.com
tags:
  - name: Configuration - Authentication
    description: AD/LDAP/RADIUS/CWP/...
paths:
  /ad-servers:
    $ref: paths/ad-servers.yaml
  /cwps:
    $ref: paths/cwps.yaml
  /ldap-servers:
    $ref: paths/ldap-servers.yaml
  /ldap-servers/{id}:
    $ref: paths/ldap-servers_{id}.yaml
  /radius-servers/internal:
    $ref: paths/radius-servers_internal.yaml
  /radius-servers/internal/{id}:
    $ref: paths/radius-servers_internal_{id}.yaml
  /radius-servers/internal/devices:
    $ref: paths/radius-servers_internal_devices.yaml
  /radius-servers/external:
    $ref: paths/radius-servers_external.yaml
  /radius-servers/external/{id}:
    $ref: paths/radius-servers_external_{id}.yaml
  /radius-proxies:
    $ref: paths/radius-proxies.yaml
  /radius-proxies/{id}:
    $ref: paths/radius-proxies_{id}.yaml
  /radius-proxies/devices:
    $ref: paths/radius-proxies_devices.yaml
  /radius-client-objects:
    $ref: paths/radius-client-objects.yaml
  /radius-client-objects/{id}:
    $ref: paths/radius-client-objects_{id}.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
