openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: User
    description: Local and external user management in ExtremeCloud IQ account
paths:
  /users/me:
    $ref: paths/users_me.yaml
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users_{id}.yaml
  /users/external:
    $ref: paths/users_external.yaml
  /users/external/{id}:
    $ref: paths/users_external_{id}.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml
