get:
  tags:
    - Application
  summary: List the TopN applications
  description: List the TopN applications by usage.
  externalDocs:
    description: API Reference
    url: >-
      https://extremecloudiq.com/api-docs/api-reference.html#_list_top_n_applications_usage
  operationId: listTopApplicationsUsage
  parameters:
    - $ref: ../../common/components/parameters/path/n.yaml
    - $ref: ../../common/components/parameters/query/startTime.yaml
    - $ref: ../../common/components/parameters/query/endTime.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/XiqTopApplicationsUsage.yaml
    default:
      $ref: ../../common/components/responses/ErrorResponse.yaml
  security:
    - BearerAuth: []
