get:
  tags:
    - Application
  summary: List the TopN clients for a application
  description: List the TopN clients by usage for a specific application.
  externalDocs:
    description: API Reference
    url: >-
      https://extremecloudiq.com/api-docs/api-reference.html#_list_top_n_clients_usage_for_one_application
  operationId: listApplicationTopClientsUsage
  parameters:
    - $ref: ../../common/components/parameters/path/id.yaml
    - $ref: ../../common/components/parameters/path/n.yaml
    - $ref: ../../common/components/parameters/query/startTime.yaml
    - $ref: ../../common/components/parameters/query/endTime.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../components/schemas/XiqApplicationTopClientsUsage.yaml
    default:
      $ref: ../../common/components/responses/ErrorResponse.yaml
  security:
    - BearerAuth: []
