openapi: 3.0.3
info:
  title: ExtremeCloud IQ API
  description:
    $ref: ../info-description.md
  termsOfService: https://www.extremenetworks.com/company/legal/terms-of-use/
  contact:
    name: Extreme Networks Support
    url: https://www.extremenetworks.com/support
    email: support@extremenetworks.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 22.4.0.0
externalDocs:
  description: API Reference
  url: https://extremecloudiq.com/api-docs/api-reference.html
servers:
  - url: '{base_url}'
    description: ExtremeCloud IQ REST API Server
    variables:
      base_url:
        description: ExtremeCloud IQ Production
        default: https://api.extremecloudiq.com
tags:
  - name: Account
    description: ExtremeCloud IQ Account
paths:
  /account/home:
    $ref: paths/account_home.yaml
  /account/external:
    $ref: paths/account_external.yaml
  /account/:switch:
    $ref: paths/account_:switch.yaml
  /account/viq:
    $ref: paths/account_viq.yaml
  /account/viq/:backup:
    $ref: paths/account_viq_:backup.yaml
  /account/viq/default-device-password:
    $ref: paths/account_viq_default-device-password.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
