openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Account
    description: ExtremeCloud IQ Account
paths:
  /account/home:
    $ref: paths/account_home.yaml
  /account/external:
    $ref: paths/account_external.yaml
  /account/:switch:
    $ref: paths/account_:switch.yaml
  /account/viq:
    $ref: paths/account_viq.yaml
  /account/viq/:backup:
    $ref: paths/account_viq_:backup.yaml
  /account/viq/default-device-password:
    $ref: paths/account_viq_default-device-password.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: JSON Web Token (JWT) based authentication
      scheme: bearer
      bearerFormat: JWT
