openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Configuration - Basic
    description: VLAN Profile/DHCP Server/...
paths:
  /vlan-profiles:
    $ref: paths/vlan-profiles.yaml
  /vlan-profiles/{id}:
    $ref: paths/vlan-profiles_{id}.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml
