openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Network Policy
    description: Unified configuration management for wireless and wired network devices
paths:
  /network-policies/{id}:
    $ref: paths/network-policies_{id}.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml
