openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Operation
    description: Long-Running Operations (LRO) management for asynchronous APIs
paths:
  /operations/{operationId}:
    $ref: paths/operations_{operationId}.yaml
  /operations/{operationId}/:cancel:
    $ref: paths/operations_{operationId}_:cancel.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml
