type: object
description: The password expiration settings
properties:
  expiration_type:
    $ref: ./XiqExpirationType.yaml
  valid_during_dates:
    $ref: ./XiqValidDuringDateSettings.yaml
  valid_for_time_period:
    $ref: ./XiqValidForTimePeriodSettings.yaml
  valid_daily:
    $ref: ./XiqValidDailySettings.yaml
  expiration_action:
    $ref: ./XiqExpirationActionType.yaml
  post_expiration_action:
    $ref: ./XiqPostExpirationAction.yaml
