required:
  - password_character_types
  - password_length
  - psk_generation_method
type: object
properties:
  enable_letters:
    type: boolean
    description: Enable use of letters
  enable_numbers:
    type: boolean
    description: Enable use of numbers
  enable_special_characters:
    type: boolean
    description: Enable use of special characters
  password_concat_string:
    type: string
    description: The password concatenated string
  psk_generation_method:
    $ref: ./XiqPskGenerationMethod.yaml
  password_character_types:
    $ref: ./XiqPasswordCharacterType.yaml
  password_length:
    type: integer
    description: The maximun password string length
    format: int32
description: The password settings ID
