type: object
description: The settings for Valid During Dates option or null for other settings.
required:
  - start_date_time
  - end_date_time
  - time_zone
properties:
  start_date_time:
    $ref: ./XiqDateTimeType.yaml
  end_date_time:
    $ref: ./XiqDateTimeType.yaml
  time_zone:
    type: string
    description: The date/time timezone
