required:
  - valid_time_period_after
type: object
properties:
  valid_time_period_after:
    $ref: ./XiqValidTimePeriodAfterType.yaml
  after_id_creation_settings:
    $ref: ./XiqValidTimePeriodAfterIdCreation.yaml
  after_first_login_settings:
    $ref: ./XiqValidTimePeriodAfterFirstLogin.yaml
description: The settings for Valid For Time Period option or null for other settings.
