type: object
description: The Application Detection Rule
properties:
  value:
    type: string
    description: The value of detection rule type
  protocol:
    $ref: ./XiqApplicationDetectionProtocol.yaml
  type:
    $ref: ./XiqApplicationDetectionType.yaml
