allOf:
  - $ref: ../../../common/components/schemas/XiqViqEntity.yaml
  - type: object
    properties:
      name:
        type: string
        description: The application name
      description:
        type: string
        description: The application description
      predefined:
        type: boolean
        description: Flag to describe whether the application is predefined or customized
      category_id:
        type: integer
        description: The category ID of application
        format: int64
      category_name:
        type: string
        description: The category name of application
      detection_rules:
        type: array
        description: The application detection rules
        items:
          $ref: ./XiqApplicationDetectionRule.yaml
