allOf:
  - $ref: ../../../common/components/schemas/XiqBaseEntity.yaml
  - type: object
    description: The sensor scan settings for the radio profile
    properties:
      enable_scan_all_channels:
        type: boolean
        description: Whether to enable scanning all channels
      dwell_time:
        type: string
        description: The dwell time in ms
      scan_channels:
        type: string
        description: The comma separated list of scan channels
