allOf:
  - $ref: ../../../common/components/schemas/XiqBaseEntity.yaml
  - type: object
    description: The Miscellaneous settings for radio profile
    properties:
      sla_throughput_level:
        type: string
        description: >-
          The Client SLA options -- "NORMAL_DENSITY", "HIGH_DENSITY"
          (performance-oriented), or "LOW_DENSITY" (coverage-oriented)
      radio_range:
        type: integer
        description: The Outdoor Deployment for signal distance from 300 to 10000 meters
        format: int32
      wmm_qos_settings:
        type: array
        description: The WMM QoS settings for various media types
        items:
          $ref: ./XiqRpWmmQosSettings.yaml
