required:
  - create_time
  - id
  - update_time
type: object
properties:
  id:
    type: integer
    description: The unique identifier
    format: int64
  create_time:
    type: string
    description: The create time
    format: date-time
  update_time:
    type: string
    description: The last update time
    format: date-time
  sla_throughput_level:
    type: string
    description: >-
      The Client SLA options -- "NORMAL_DENSITY", "HIGH_DENSITY"
      (performance-oriented), or "LOW_DENSITY" (coverage-oriented)
  radio_range:
    type: integer
    description: The Outdoor Deployment for signal distance from 300 to 10000 meters
    format: int32
  wmm_qos_settings:
    type: array
    description: The WMM QoS settings for various media types
    items:
      $ref: ./XiqRpWmmQosSettings.yaml
description: The payload of config for the radio profile
