type: object
properties:
  sla_throughput_level:
    type: string
    description: >-
      The Client SLA options -- "NORMAL_DENSITY", "HIGH_DENSITY"
      (performance-oriented), or "LOW_DENSITY" (coverage-oriented)
  radio_range:
    maximum: 10000
    minimum: 300
    type: integer
    description: The Outdoor Deployment for signal distance from 300 to 10000 meters
    format: int32
