name: Auto build and commit OpenAPI definition

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-AutoCommit-OpenAPI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build OpenAPI
        run: pnpm build

      - name: Auto Commit xcloudiq-openapi.yaml
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Update OpenAPI definition
          file_pattern: xcloudiq-openapi.yaml
          commit_user_email: github-actions[bot]@extremenetworks.com
